parameters:
#    footballbet.example.class: Football\FootballbetBundle\Example

services:
#    footballbet.example:
#        class: %footballbet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
